import styles from "../styles/Home.module.css";
import React from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";

import { ACTION_TYPES } from "../redux/actions/countriesAction";

export default function Home() {
  const dispatch = useDispatch(); 
  // Using the useSelector Hook to fetch the state from store.
  const fetchedCountries = useSelector((state) => state.countries.countriesList);

  React.useEffect(() => {
    dispatch({
      type: ACTION_TYPES.FETCH_COUNTRIES,
    });
    console.log(fetchedCountries);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>All Countries</h1>
        {fetchedCountries?.map((c) => (
          <h3 key={c.name}>{c.name}</h3>
        ))}
      </main>
    </div>
  );
}
